name: Dependency Review

on:
  pull_request: {}

permissions:
  contents: read
  pull-requests: read

jobs:
  review:
    name: Review dependency changes
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10

      - name: Review dependency diff
        uses: actions/dependency-review-action@1e966ba708e4b64bb0c9bfb7abb5a232840be16a
        with:
          fail-on-severity: high
